# Generated by Django 3.0.10 on 2024-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0002_expense_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
