# Generated by Django 3.0.10 on 2024-09-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_budget', '0007_auto_20240907_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
